[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/",
    "forge-std/=lib/forge-std/src/"
]

# Compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
fuzz_runs = 256
fuzz_max_test_rejects = 65536

# Gas settings
gas_limit = 9223372036854775807
gas_price = 20000000000

# RPC settings (optional - only needed for deployment)
# eth_rpc_url = "${ETH_RPC_URL}"
# sepolia_rpc_url = "${SEPOLIA_RPC_URL}"
# polygon_rpc_url = "${POLYGON_RPC_URL}"
# arbitrum_rpc_url = "${ARBITRUM_RPC_URL}"
# base_rpc_url = "${BASE_RPC_URL}"
# avalanche_rpc_url = "${AVALANCHE_RPC_URL}"

# Etherscan API keys for verification (optional)
# etherscan_api_key = "${ETHERSCAN_API_KEY}"
# polygonscan_api_key = "${POLYGONSCAN_API_KEY}"
# arbiscan_api_key = "${ARBISCAN_API_KEY}"
# basescan_api_key = "${BASESCAN_API_KEY}"
# snowtrace_api_key = "${SNOWTRACE_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
